name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Fetch all branches
          run: git fetch --all
          
        - name: Check changed files
          id: changed-files
          run: |
            echo "::set-output name=files::$(git diff --name-only --diff-filter=ACMRTUXB origin/dev...origin/${{ github.head_ref }} | grep \\.php$ | tr '\n' ' ')"
        
        - name: Changed File Print
          run: echo "${{ steps.changed-files.outputs.files }}"
            
        - name: WPCS check
          if: ${{ steps.changed-files.outputs.changed_files > 0 }}
          uses: 10up/wpcs-action@stable
          with:
            repo_branch: 'dev' # Branch of Standard repository
            paths: "${{ steps.changed-files.outputs.files }}" # Paths to check, space separated like ./views ./classes ./models
            excludes: '' # Paths to excludes, space separated
            standard: 'WordPress' # Coding standard
            enable_warnings: 'false' # Enable checking for warnings (-w)
            use_local_config: 'false' # Use local config if available
            extra_args: '-d error_reporting="E_ALL&~E_DEPRECATED"'